### PR TITLE
fix hints

### PR DESCRIPTION
**Pull request by thery**

### CODE REVIEW

**Comment by JasonGross** [comment]
I think this breaks the build on Coq 8.12 and 8.13.  Maybe there should be a CI job testing these?  (Do you want me to make a PR setting up CI here?)

**Comment by thery** [comment]
please do

**Comment by JasonGross** [comment]
I'll aim to submit a PR within the next day or so

**Comment by thery** [comment]
yes, travis tells me I have no credit :disappointed:

**Pull request merged**
