### PR TITLE
add primality-related results from Goedel project

### PR DESCRIPTION
**Pull request by palmskog**
Includes Chinese remainder theorem and variants.

cc: @Casteran

### CODE REVIEW

**Comment by palmskog** [comment]
CI failure on 8.11 looks unrelated:
```
  # File "./plugins/micromega/Zify.v", line 90, characters 13-20:
  # Error: Tactic failure:  Cannot find witness.
```
I thought CoqPrime didn't even support 8.11 any more?

**Comment by thery** [comment]
@palmskog strange this failure for 8.11. I will try to look at it

**Comment by palmskog** [comment]
Ah, it may actually be related to use of `lia` in the new file in 8.11, which I believe was not very mature at that point. I'll see if I can reproduce tonight.

**Comment by thery** [comment]
I think I add a fix, lia is called on some non-linear stuff. Moving some lia into nia seems to work in 8.11

**Pull request merged**
