### PR TITLE
Adapt w.r.t. coq/coq#16004.

### PR DESCRIPTION
**Pull request by ppedrot**
Alternative to #47 that is compatible up to Coq 8.11.

### CODE REVIEW

**Comment by JasonGross** [comment]
Coils we merge #49 (CI fix) and #51(test Fiat Crypto Legacy target after removing #[global] in CI) first, and then rebase this to get a clean CI, and then merge this?

**Comment by thery** [comment]
I am a bit lost what should I do?

**Comment by JasonGross** [comment]
It seems there were errors in the other PRs; I've created #55 and #56 to fix those errors; could you merge these PRs (#56 should hopefully fix the legacy build job, and #55 should hopefully fix the normal build job), and then you or @ppedrot can rebase this on top of master, and hopefully the CI will finally pass and we can merge this

**Comment by JasonGross** [comment]
Hm, seems like #56 wasn't enough, but hopefully #57 will be.  We'll still need to have @ppedrot rebase this on top of master / #57, though, I think

**Pull request merged**
