### PR TITLE
Adapt to coq/coq#15754

### PR DESCRIPTION
**Pull request by proux01**
This bumps minimal Coq version to 8.14.

### CODE REVIEW

**Comment by thery** [comment]
My only problem for merging is that fiat crypto would like to keep the support for 8.11. [See](https://github.com/thery/coqprime/pull/42). @JasonGross is it still the case?

**Comment by proux01** [comment]
@JasonGross do you need master to keep supporting 8.11 or would a release be enough?

We managed to keep support down to 8.7 in Flocq, but that's using some autoconf wizardry that no one really enjoys.

**Comment by JasonGross** [comment]
The problem with a release supporting 8.11 is that we want to use the same version of coqprime to support both master and Ubuntu LTS.  Is there no backwards compatible change? :-/. (If you're willing, I could code up a version-dependent shim file that just Exported the appropriate standard library file.)

**Comment by proux01** [comment]
You can take inspiration of the Flocq overlay, but that's painful: https://gitlab.inria.fr/flocq/flocq/-/merge_requests/19

**Comment by thery** [comment]
@proux01 too complicate for me ....

**Comment by JasonGross** [comment]
Sorry for the delay, I will prepare a PR shortly

**Comment by thery** [comment]
@proux and @JasonGross we can close this thanks to #45, no?

**Comment by proux01** [comment]
Indeed

**Pull request closed without merging**
