### PR TITLE
Adapt to coq/coq#16920

### PR DESCRIPTION
**Pull request by olaure01**
Use `Zdiv.Z_div_mod_eq_full` instead of deprecated `Zdiv.Z_div_mod_eq` (coq/coq#16920).

### CODE REVIEW

**Comment by olaure01** [comment]
Note the corresponding overlay mit-plv/fiat-crypto#1529 has already been merged in fiat-crypto.
I see 3 possibles ways to go which partly depend on your plans about compatibility with old Coq versions (note the PR coq/coq#16920 will not be integrated before Coq 8.17 and probably not before 8.18). Do you have precise plans wrt compatibility with different Coq versions?
Possible directions are:
* lose compatibility with Coq <8.14
* move to something compatible with more Coq versions by relying on `Z.div_mod` (but this is more a move to the past than towards the future) (tested [here](https://github.com/olaure01/CompCert/commit/f830fcca70a4e80200b53aa844b98ee131c7c42b) for another project for example)
* make the overlay code a bit more weird and compatible with more versions but anyway using `Zdiv.Z_div_mod_eq_full` in recent ones

**Comment by thery** [comment]
@JasonGross I am puzzled, is fiat-crypto tested on less versions than coqprime?

**Comment by JasonGross** [comment]
Yes, fiat-crypto-legacy dropped support for Coq < 8.14 in https://github.com/mit-plv/fiat-crypto/pull/1540, and fiat-crypto (non-legacy) dropped support for Coq < 8.15 in https://github.com/mit-plv/fiat-crypto/pull/1361.  So feel free to drop support for Coq < 8.14 now

**Comment by thery** [comment]
@olaure01 Thanks!

**Comment by thery** [comment]
@JasonGross  Thanks

**Pull request merged**
