### PR TITLE
Adapt w.r.t coq/coq#16004

### PR DESCRIPTION
**Pull request by Alizter**

### CODE REVIEW

**Comment by JasonGross** [comment]
This is going to break fiat-crypto.  Please at least suppress the `unsupported-attributes` warning.

**Comment by ppedrot** [comment]
@JasonGross this will only provide compatibility with Coq >= 8.11 though. How far are you willing to support the old Coq versions in fiat-crypto?

**Comment by ppedrot** [comment]
@JasonGross see #48 for an alternative. If you're happy with this we should make some progress quickly because this issue is going to be more annoying by the minute.

**Comment by ppedrot** [comment]
@Alizter you should probably close this PR because #48 subsumes it. (The choice between #48 and #52 is orthogonal though.)

**Pull request closed without merging**
